export type Language = 'es' | 'en';

export const translations = {
  es: {
    nav_home: "Inicio",
    nav_menu: "Menú Completo",
    nav_social: "¡No te pierdas esto!",
    nav_about: "Nosotros",
    nav_call: "Llamar",
    nav_call_now: "Llamar Ahora",
    btn_lang_home: "Click here for English",
    btn_lang_social: "Click here to switch to English",
    switchMsg: "Want to see the menu in English?",
    btnLabel: "Click here for English",
    home_subtitle: "La Casa del Metro",
    home_desc: "Famosos por nuestras <span class='text-km-gold font-bold'>Pizzas Gigantes</span> <br> en Tabla de Madera. <br class='hidden xs:block'> El sabor que se comparte metro a metro.",
    btn_view_menu: "Ver Menú Completo",
    btn_call_now: "Llamar Ahora",
    metro_badge: "Nuestra Insignia",
    metro_title_1: "NO ES SOLO PIZZA,",
    metro_title_2: "ES UN",
    metro_title_3: "ESPECTÁCULO",
    metro_desc_1: "En <strong>Kilómetro Pizza</strong>, servimos en <span class='text-km-gold font-bold border-b border-km-gold'>tablas de madera rústica</span> de hasta <strong>1 Metro</strong>.",
    metro_point_1: "Servidas en tablas de madera de 1 metro.",
    metro_point_2: "Perfectas para grandes grupos.",
    metro_point_3: "Hasta 4 sabores en una pizza.",
    loc_badge: "Ubicación Estratégica",
    loc_title: "Lugares Cercanos",
    loc_desc: "Costa Dorada, Puerto Plata.",
    btn_gps: "LLEGA LO MÁS RÁPIDO POSIBLE (GPS)",
    hungry_txt: "¿Tienes Hambre?",
    menu_title_main: "HORA DE <br class='md:hidden'> DISFRUTAR",
    cat_clasicos: "Clásicos",
    cat_especialidades: "Especialidades",
    cat_nuevas: "Nuevas",
    cat_hamburguesas: "Hamburguesas",
    cat_bebidas: "Bebidas",
    tap_price: "¡Toca para ver precio!",
    social_title: "¡NO TE PIERDAS ESTO!",
    social_card_title: "Ofertas Exclusivas",
    social_card_desc: "¡Únete a nuestra comunidad en Instagram y sé parte de la gran <strong>familia KM Pizza</strong>! Comparte tus momentos y mantente al día con todas nuestras novedades.",
    btn_follow: "Seguir a @kmpizzaburger",
    social_footer: "Únete a más de 2,000 amantes de la pizza",
    footer_contact_title: "Ubicación & Contacto",
    footer_map_btn: "Abrir Mapa (GPS)",
    footer_slogan: "Pizzas Gigantes en Puerto Plata"
  },
  en: {
    nav_home: "Home",
    nav_menu: "Full Menu",
    nav_social: "Don't Miss This!",
    nav_about: "About Us",
    nav_call: "Call",
    nav_call_now: "Call Now",
    btn_lang_home: "Pulsa aquí para cambiar a Español",
    btn_lang_social: "¡Pulsa aquí para cambiar a Español!",
    switchMsg: "¿Quieres ver el menú en Español?",
    btnLabel: "Pulsa aquí para Español",
    home_subtitle: "Home of the Meter Pizza",
    home_desc: "Famous for our <span class='text-km-gold font-bold'>Giant Pizzas</span> <br> on Wooden Boards. <br class='hidden xs:block'> Flavor shared meter by meter.",
    btn_view_menu: "View Full Menu",
    btn_call_now: "Call Now",
    metro_badge: "Our Signature",
    metro_title_1: "IT'S NOT JUST PIZZA,",
    metro_title_2: "IT'S A",
    metro_title_3: "SPECTACLE",
    metro_desc_1: "At <strong>Kilómetro Pizza</strong>, we serve on <span class='text-white font-bold border-b border-km-gold'>rustic wooden boards</span> up to <strong>1 Meter</strong> long.",
    metro_point_1: "Served on 1-meter wooden boards.",
    metro_point_2: "Perfect for large groups.",
    metro_point_3: "Up to 4 flavors in one pizza.",
    loc_badge: "Strategic Location",
    loc_title: "Nearby Places",
    loc_desc: "Costa Dorada, Puerto Plata.",
    btn_gps: "GET HERE FAST (GPS)",
    hungry_txt: "Are You Hungry?",
    menu_title_main: "TIME TO <br class='md:hidden'> ENJOY",
    cat_clasicos: "Classics",
    cat_especialidades: "Specialties",
    cat_nuevas: "New Creations",
    cat_hamburguesas: "Burgers",
    cat_bebidas: "Drinks",
    tap_price: "Tap to see price",
    social_title: "DON'T MISS THIS!",
    social_card_title: "Exclusive Offers",
    social_card_desc: "Join our Instagram community and be part of the big <strong>KM Pizza family</strong>! Share your moments and keep up with all our news.",
    btn_follow: "Follow @kmpizzaburger",
    social_footer: "Join over 2,000 pizza lovers",
    footer_contact_title: "Location & Contact",
    footer_map_btn: "Open Map (GPS)",
    footer_slogan: "Giant Pizzas in Puerto Plata"
  }
};

export const menuData = [
  // --- CLÁSICOS ---
  { id: 1, name: "Jamón y Queso", name_en: "Ham & Cheese", category: "clasicos", ingredients: "Jamón Premium y Queso", ingredients_en: "Premium Ham and Cheese", image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=600&q=80", prices: { small: 480, medium: 865, large: 1410 } },
  { id: 2, name: "Pepperoni", name_en: "Pepperoni", category: "clasicos", ingredients: "Doble Pepperoni", ingredients_en: "Double Pepperoni", image: "https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=600&q=80", prices: { small: 480, medium: 865, large: 1410 } },
  { id: 3, name: "Pollo y Queso", name_en: "Chicken & Cheese", category: "clasicos", ingredients: "Pollo y Queso", ingredients_en: "Chicken and Cheese", image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80", prices: { small: 480, medium: 865, large: 1410 } },
  { id: 4, name: "Tocino y Queso", name_en: "Bacon & Cheese", category: "clasicos", ingredients: "Bacon crujiente", ingredients_en: "Crispy Bacon", image: "https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?auto=format&fit=crop&w=600&q=80", prices: { small: 480, medium: 865, large: 1410 } },
  { id: 5, name: "Salchichas", name_en: "Sausage", category: "clasicos", ingredients: "Salchichas y Queso", ingredients_en: "Sausage and Cheese", image: "https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?auto=format&fit=crop&w=600&q=80", prices: { small: 480, medium: 865, large: 1410 } },
  { id: 6, name: "4 Quesos", name_en: "4 Cheeses", category: "clasicos", ingredients: "Mozzarella, Manchego, Parmesano", ingredients_en: "Mozzarella, Manchego, Parmesan", image: "https://images.unsplash.com/photo-1573821663912-6df460f9c684?auto=format&fit=crop&w=600&q=80", prices: { small: 515, medium: 930, large: 1535 } },

  // --- ESPECIALIDADES ---
  { id: 7, name: "Completa", name_en: "The Works", category: "especialidades", ingredients: "Carne, pepperoni, jamón, vegetales", ingredients_en: "Beef, pepperoni, ham, veggies", image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=600&q=80", prices: { small: 530, medium: 915, large: 1460 } },
  { id: 8, name: "Barbacoa", name_en: "BBQ", category: "especialidades", ingredients: "Salsa barbacoa, carnes", ingredients_en: "BBQ Sauce, meats", image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80", prices: { small: 515, medium: 930, large: 1535 } },
  { id: 9, name: "Mar y Granja", name_en: "Surf & Turf", category: "especialidades", ingredients: "Camarones y Pollo", ingredients_en: "Shrimp and Chicken", image: "https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=600&q=80", prices: { small: 575, medium: 1025, large: 1655 } },
  { id: 10, name: "Infierno", name_en: "Inferno", category: "especialidades", ingredients: "Picante y Salami", ingredients_en: "Spicy oil and Salami", image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=80", prices: { small: 450, medium: 835, large: 1280 } },
  { id: 11, name: "Carbonara", name_en: "Carbonara", category: "especialidades", ingredients: "Salsa blanca y bacon", ingredients_en: "White sauce and bacon", image: "https://images.unsplash.com/photo-1605478371310-a9f1e96b4ff4?auto=format&fit=crop&w=600&q=80", prices: { small: 510, medium: 930, large: 1535 } },
  { id: 12, name: "Napolitana", name_en: "Neapolitan", category: "especialidades", ingredients: "Anchoas y aceitunas", ingredients_en: "Anchovies and olives", image: "https://images.unsplash.com/photo-1576458088443-04a19bb13da6?auto=format&fit=crop&w=600&q=80", prices: { small: 515, medium: 930, large: 1535 } },

  // --- NUEVAS ---
  { id: 13, name: "Hawaiana", name_en: "Hawaiian", category: "nuevas", ingredients: "Piña y Jamón", ingredients_en: "Pineapple and Ham", image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=600&q=80", prices: { small: 385, medium: 640, large: 1150 } },
  { id: 14, name: "Tex Mex", name_en: "Tex Mex", category: "nuevas", ingredients: "Picante y carne molida", ingredients_en: "Spicy and ground beef", image: "https://images.unsplash.com/photo-1590947132387-155cc02f3212?auto=format&fit=crop&w=600&q=80", prices: { small: 480, medium: 865, large: 1410 } },
  { id: 15, name: "Margarita", name_en: "Margherita", category: "nuevas", ingredients: "Tomate y Albahaca", ingredients_en: "Tomato and Basil", image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=600&q=80", prices: { small: 350, medium: 575, large: 1025 } },
  { id: 16, name: "Serrana", name_en: "Serrano", category: "nuevas", ingredients: "Jamón serrano", ingredients_en: "Serrano ham", image: "https://images.unsplash.com/photo-1588315029754-2dd089d39a1a?auto=format&fit=crop&w=600&q=80", prices: { small: 515, medium: 930, large: 1535 } },
  { id: 17, name: "Salmón", name_en: "Salmon", category: "nuevas", ingredients: "Salmón y Guacamole", ingredients_en: "Salmon and Guacamole", image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80", prices: { small: 575, medium: 1025, large: 1665 } },

  // --- HAMBURGUESAS ---
  { id: 18, name: "KM Burger", name_en: "KM Burger", category: "hamburguesas", ingredients: "Carne Angus", ingredients_en: "Angus Beef", image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80", priceSingle: 350 },
  { id: 19, name: "Bacon Lovers", name_en: "Bacon Lovers", category: "hamburguesas", ingredients: "Mucho Tocino", ingredients_en: "Lots of Bacon", image: "https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?auto=format&fit=crop&w=600&q=80", priceSingle: 450 },

  // --- BEBIDAS ---
  { id: 20, name: "Refresco 2L", name_en: "Soda 2L", category: "bebidas", ingredients: "Coca Cola, etc", ingredients_en: "Coke, Sprite, etc", image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80", priceSingle: 150 },
  { id: 21, name: "Cerveza", name_en: "Beer", category: "bebidas", ingredients: "Presidente", ingredients_en: "Presidente", image: "https://images.unsplash.com/photo-1567696911980-2eed69a46042?auto=format&fit=crop&w=600&q=80", priceSingle: 250 },
  { id: 22, name: "Jugos", name_en: "Juices", category: "bebidas", ingredients: "Naturales", ingredients_en: "Natural Juices", image: "https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=600&q=80", priceSingle: 120 }
];
